# Generated by Django 3.2.3 on 2021-05-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.JSONField(default='{}'),
        ),
    ]
